#!/bin/csh

# start up Xvfb for screen 7

set echo=true
set matlab_data_dir=~/projDir/data/matlab
set sounding_data_dir=${matlab_data_dir}/sounding
set script_dir=~/projDir/matlab/scripts/repoh

snuff "Xvfb :7.0"
Xvfb :7.0 -screen 0 1600x1200x24 -pixdepths 24 -ac -ld 2000000 -bs -ls 10000 |& \
  LogFilter -d $ERRORS_LOG_DIR -p Xvfb -i display_9 >& /dev/null &
  sleep 2
endif

# set display to 7

setenv DISPLAY :7.0

# set start and end dates

set startDate = 20111201
set endDate = 20111223

# make plot for Diego

plotSoundingTimeseries.py --debug \
    --soundingDataDir ${sounding_data_dir} \
    --siteSubDir diego \
    --siteName "Diego Garcia" \
    --startDate ${startDate} \
    --endDate ${endDate} \
    --outputImageDir /tmp/catalogimages \
    --matlabPath /usr/local/MATLAB/R2011a/bin/matlab \
    --minNcFileSize 60000

end

# kill X server

snuff "Xvfb :7.0"

