#! /bin/bash
#
# Name: get_host_type
#
# Purpose: print the host type by interpreting the host name.
#
#====================================================================

THIS_HOST=`hostname`

case ${THIS_HOST} in
	rvp8.gate.rtf) host_type=rvp8;;
	mgen.gate.rtf) host_type=mgen;;
	pgen.gate.rtf) host_type=pgen;;
	eng.gate.rtf) host_type=eng;;
	iq.gate.rtf) host_type=display;;
	iris.gate.rtf) host_type=display;;
	spol-gate.gate.rtf) host_type=web_server;;
	**) host_type=${THIS_HOST};;
esac

echo $host_type

exit 0

