#!/bin/csh

runRadxCov2Mom.py --debug --start "2011 10 01 00 00 00" --end "2011 11 01 00 00 00" --paramsDir $PROJ_DIR/alg/params >& $DATA_DIR/logs/runRadxCov2Mom.py.2011_10 &

runRadxCov2Mom.py --debug --start "2011 11 01 00 00 00" --end "2011 12 01 00 00 00" --paramsDir $PROJ_DIR/alg/params >& $DATA_DIR/logs/runRadxCov2Mom.py.2011_11 &

runRadxCov2Mom.py --debug --start "2011 12 01 00 00 00" --end "2012 01 01 00 00 00" --paramsDir $PROJ_DIR/alg/params >& $DATA_DIR/logs/runRadxCov2Mom.py.2011_12 &

runRadxCov2Mom.py --debug --start "2012 01 01 00 00 00" --end "2012 01 16 00 00 00" --paramsDir $PROJ_DIR/alg/params >& $DATA_DIR/logs/runRadxCov2Mom.py.2012_01 &



