#! /bin/csh -f

# run vert compute for today's data

set today=`date +%Y%m%d`

echo Running vert compute for day: $today

cd ~/projDir/analysis/params

VertCompute -params VertCompute.zdr -f $DATA_DIR/tsarchive/vert/${today}/*.tsarchive -debug

